package com.dzmitry.spark

import org.apache.log4j.{Level, Logger}
import org.apache.spark.sql.SparkSession


object MostPopularMovie {

  def returnMovie(line:String): (String,Int) = {
    val movieId = line.split("\t")(1)
    print(movieId)
    (movieId,1)
  }

  def main(args: Array[String]): Unit = {

    Logger.getLogger("org").setLevel(Level.ERROR)
    val spark = SparkSession.builder
      .appName("Word Count")  // optional and will be autogenerated if not specified
      .master("local[*]")               // only for demo and testing purposes, use spark-submit instead
      .config("spark.sql.warehouse.dir", "target/spark-warehouse")
      .getOrCreate()

    val lines = spark.sparkContext.textFile("../ml-100k/u.data")
    val mostPopularMovies = lines.map(returnMovie)
//      Make counts
      .reduceByKey((x,y)=>(x+y))
//      reverse
      .map(x =>(x._2,x._1))
//      sort
      .sortByKey(false)
//      reverse back
      .map(x => (x._2,x._1))

    val df = spark.createDataFrame(mostPopularMovies).toDF("Movie","RaitedTimes")
    df.show()
  }
}
